### ISSUE TITLE
doom3 logo block of static

### ISSUE THREAD

**Issue by GoogleCodeExporter** [blackbeard334/djoom3#1]
```
To reproduce:
1. Comment line number 959 in draw_common.java(HACKME::4).

Instead of our beloved animated doom3 logo, we get an animated block of 
animated(scrolling) vertical static lines.
It appears as if something is going on with the blending process.

To reproduce in the c++ version:
1. Comment line 339 of tr_backend.cpp(GL_STATE).
```

Original issue reported on code.google.com by `nmax...@gmail.com` on 7 Feb 2015 at 8:17
- Blocking: #6

Attachments:
- [title_static.png](https://storage.googleapis.com/google-code-attachments/djoom3/issue-1/comment-0/title_static.png)

**Comment by blackbeard334** [comment]
This might be a driver issue, since it works on some computers.
Also, it stopped working on a certain machine after some updates.

**Comment by blackbeard334** [comment]
This only happens with nvidia drivers.

Workaround found by using lwjgl3
