### ISSUE TITLE
cd key message box missing all text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [blackbeard334/djoom3#8]
```
All text except "D3 Key" is missing, and the buttons/actions don't seem to work.
```

Original issue reported on code.google.com by `nmax...@gmail.com` on 19 Mar 2015 at 8:26

**Comment by blackbeard334** [comment]
The WinVar(and descendants) copy constructors were missing some stuff from their respective **&operator=** counterparts.

**Comment by blackbeard334** [comment]
213
1314
217 245

saveGameDifficulty
DBG_id
126
239
DBG_COUNT
919

-copy constructors!

idWindow.Redraw:1889
bla2==3704
DBG_count==1274

idSimpleWindow.text.data is updated in idWindow.UpdateWinVars()

text("title").DBG_id==140702               1890    1948    1966    1272    10670
text("message").DBG_id==140826      1890    1948    1966    1274    10680
1272 RDGTitleText   3164 3173
1274 RDGText        3188 3191
1966 RDG
1948 CDKeyMain
1890 Desktop

//-appended to drawWindows in idWindow.Parse()
//how do drawWindows become children?
//possible answer, idWindow.GetChild()
//ignore this shit above

when we reach idWindow.Redraw(), the text.data of 1274(look up) is empty, but has the same object ref.
sombody is fucking iwth us!!
-note that text.data is still empty at the point of inception.
-seems text.data is updated in idWindow.UpdateWinVars()
-1966 should have 2 updateVars, but has 1 instaed!!!! the humanity!
-addUnique() is failing us lads. 
-idWinvars equals is comparing the wrong stuff

![https://raw.githubusercontent.com/blackbeard334/djoom3/wiki/bug8_1.png](https://raw.githubusercontent.com/blackbeard334/djoom3/wiki/bug8_1.png)
